name: Single-Package CI Build

on:
  workflow_call:
    inputs:
      caller_event_name:
        required: true
        type: string
        description: "Flag to distinguish between e.g. schedule and pull request"

env:
  CALLER_BRANCH: ${{ github.head_ref || github.ref_name }}
  TARGET_BRANCH: ${{ github.base_ref || github.ref_name }}

jobs:
  Should_run:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:

      - name: checkout package for CI
        uses: actions/checkout@main
        with:
          path: ${{ github.repository }}

      - id: check
        run: |
          if [[ "$CALLER_BRANCH" != "$TARGET_BRANCH" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else

            cd $GITHUB_WORKSPACE/${{ github.repository }}
            git checkout $TARGET_BRANCH
            commit_time=$( git log -1 --format=%ct )
            current_time=$( date +%s )

            time_since_last_commit=$(( current_time - commit_time ))
            max_time_since_push=90

            if (( $time_since_last_commit > $max_time_since_push )); then
              echo "should_run=true" >> $GITHUB_OUTPUT
            else
              echo "should_run=false" >> $GITHUB_OUTPUT
              echo "Single repo CI will not proceed as this appears to be triggered by a merge or a push (last commit to $TARGET_BRANCH was $time_since_last_commit seconds ago)"
              exit 0
            fi
          fi

  Determine_image:
    needs: Should_run
    if: needs.Should_run.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
      - id: set_image
        run: |
          if [[ "$TARGET_BRANCH" =~ ^prep-release/.* ]]; then
            echo "image=ghcr.io/dune-daq/candidate-release-alma9:latest" >> $GITHUB_OUTPUT
          elif [[ "$TARGET_BRANCH" =~ ^patch/.* ]]; then
            echo "image=ghcr.io/dune-daq/stable-release-alma9:latest" >> $GITHUB_OUTPUT
          else
            echo "image=ghcr.io/dune-daq/nightly-release-alma9:development_v5" >> $GITHUB_OUTPUT
          fi

  Build_against_dev_release:
    needs: Determine_image
    name: build_against_dev_on_${{ matrix.os_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ${{ needs.determine_image.outputs.image }}
            os_name: "a9"
    defaults:
      run:
        shell: bash

    steps:
    
    - name: Checkout daq-release
      uses: actions/checkout@main
      with:
        repository: DUNE-DAQ/daq-release
        path: daq-release

    - uses: cvmfs-contrib/github-action-cvmfs@v5
      with:
        cvmfs_repositories: 'dunedaq-development.opensciencegrid.org'

    - name: Pull build image
      run: docker pull ${{ needs.determine_image.outputs.image }}
        
    - id: get_release_info
      run: |
          echo "Caller branch is " "$CALLER_BRANCH"
          echo "Target branch is " "$TARGET_BRANCH"
          export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')

          extra_dbt_args=""
          if [[ ${{ needs.determine_image.outputs.image }} =~ ^.*stable.* ]]; then
            release_name=$( ls -tr /cvmfs/dunedaq.opensciencegrid.org/spack/releases/ | grep fddaq | tail -1 )
          elif [[ ${{ needs.determine_image.outputs.image }} =~ ^.*candidate.* ]]; then
            extra_dbt_args="-b candidate"
            release_name=$( ls -tr /cvmfs/dunedaq-development.opensciencegrid.org/candidates/ | grep fddaq | tail -1 )
          else
            extra_dbt_args="-n"
            release_name=$( ls -tr /cvmfs/dunedaq-development.opensciencegrid.org/nightly/ | grep fddaq | tail -1 )
          fi

          echo "extra_dbt_args=$extra_dbt_args" >> "$GITHUB_OUTPUT"
          echo "release_name=$release_name"     >> "$GITHUB_OUTPUT"

    - name: checkout package for CI
      uses: actions/checkout@main
      with:
        path: ${{ github.repository }}

    - name: setup build env, build the repo against the development release
      run: |
          BRANCH="$CALLER_BRANCH"

          export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
          #cd $GITHUB_WORKSPACE/dev-${{ matrix.os_name }}

          echo "Before script: $(pwd)"

          cat << EOF > build_and_lint_package.sh
          #!/bin/bash

          source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest

          echo "Creating in container: $(pwd)"
          dbt-create ${{ steps.get_release_info.outputs.extra_dbt_args }} \
                     ${{ steps.get_release_info.outputs.release_name}} \
                     dev-${{ matrix.os_name }}

          echo "Build area?: $(ls)"
          cd dev-${{ matrix.os_name }}
          echo "Now in: $(pwd)"
          source env.sh

          cd sourcecode
          if [[ "$CALLER_BRANCH" == "$TARGET_BRANCH" ]]; then
            cp -pr /ghw/DUNE-DAQ/$REPO .
          else   # Someone opened a PR
            export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            /ghw/daq-release/scripts/clone_all_packages_with_branch.py --branch $CALLER_BRANCH --package-group coredaq
            /ghw/daq-release/scripts/clone_all_packages_with_branch.py --branch $CALLER_BRANCH --package-group fddaq
          fi

          if [[ -d "./dbe" ]]; then
            spack load dbe
          fi

          dbt-workarea-env
          dbt-info sourcecode
          dbt-build --lint
          EOF

          chmod +x build_and_lint_package.sh

          docker run --rm \
            -v /cvmfs:/cvmfs:shared \
            -v "${GITHUB_WORKSPACE}:/ghw" \
            -w /ghw \
            ${{ needs.determine_image.outputs.image }} \
            /ghw/build_and_lint_package.sh

    - name: upload build log file
      uses: actions/upload-artifact@main
      with:
        name: build_log_${{ matrix.os_name }}
        path: ${{ github.workspace }}/dev-${{ matrix.os_name }}/log/build*.log

    - name: set linting artifact name
      id: set_artifact_name
      run: |
        linting_artifact_name="pull_request_linting_results"
        if [[ ${{ inputs.caller_event_name == 'schedule' }} ]]; then
          linting_artifact_name="nightly_linting_results"
        fi
        echo "linting_artifact_name=$linting_artifact_name" >> "$GITHUB_OUTPUT"

    - name: upload linting log file
      uses: actions/upload-artifact@main
      with:
        name: ${{ steps.set_artifact_name.outputs.linting_artifact_name }}
        path: ${{ github.workspace }}/dev-${{ matrix.os_name }}/log/linting*/*_linting.log
  
  compare_linting_results:
    if: ${{ inputs.caller_event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Get ID of latest nightly run
      id: latest_nightly
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        run_id=$(gh run list \
          --repo ${{ github.repository }}
          --workflow dunedaq-develop-cpp-ci.yml \
          --event schedule \
          --limit 1 \
          --json databaseId \
          --jq '.[0].databaseId')

        echo "run_id=$run_id" >> "$GITHUB_OUTPUT"

    - name: Download latest nightly linting results
      uses: actions/download-artifact@main
      with:
        name: nightly_linting_results
        run-id: ${{ steps.latest_nightly.outputs.run_id }}

    - name: Download pull request linting results
      uses: actions/download-artifact@main
      with:
        name: pull_request_linting_results

    - name: Compare linting results
      id: compare
      continue-on-error: true
      run: |
        diff_file_name=linting_diff.txt
        pr_linting_results_file=$(dev-${{ matrix.os_name }}/log/linting*/*_linting.log)
        nightly_linting_results_file=$(dev-${{ matrix.os_name }}/nightly_linting_results.log)

        [[ -f "$pr_linting_results_file" ]] || echo "ERROR: No PR results file; exit 1"
        [[ -f "$nightly_linting_results_file" ]] || echo "ERROR: No nightly results file; exit 2"

        if ! diff "$pr_linting_results_file" "$nightly_linting_results_file" > "$diff_file_name"; then
          echo "ERROR: This PR introduces new linting errors:"
          cat "$diff_file_name"
          echo "diff_file_name=$diff_file_name" >> "$GITHUB_OUTPUT"
          exit 1
        fi

    - name: upload linting diff file
      if: steps.compare.outputs.diff_file_name
      uses: actions/upload-artifact@main
      with:
        name: linting_diff
        path: ${{ steps.compare.outputs.diff_file_name }}
