name: Single-Package CI Build and Linting

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      caller_event_name:
        required: true
        type: string
        description: "Flag to distinguish between e.g. schedule and pull request"

env:
  CALLER_BRANCH: ${{ github.head_ref || github.ref_name }}
  TARGET_BRANCH: ${{ github.base_ref || github.ref_name }}
  REPO: ${{ github.event.repository.name }}

jobs:
  Should_run:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:

      - name: checkout package for CI
        uses: actions/checkout@v7
        with:
          path: ${{ github.repository }}

      - id: check
        run: |
          if [[ "$CALLER_BRANCH" != "$TARGET_BRANCH" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else

            cd $GITHUB_WORKSPACE/${{ github.repository }}
            git checkout $TARGET_BRANCH
            commit_time=$( git log -1 --format=%ct )
            current_time=$( date +%s )

            time_since_last_commit=$(( current_time - commit_time ))
            max_time_since_push=90

            if (( $time_since_last_commit > $max_time_since_push )); then
              echo "should_run=true" >> $GITHUB_OUTPUT
            else
              echo "should_run=false" >> $GITHUB_OUTPUT
              echo "Single repo CI will not proceed as this appears to be triggered by a merge or a push (last commit to $TARGET_BRANCH was $time_since_last_commit seconds ago)"
              exit 0
            fi
          fi

  Determine_image:
    needs: Should_run
    if: needs.Should_run.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
      - id: set_image
        run: |
          if [[ "$TARGET_BRANCH" =~ ^prep-release/.* ]]; then
            echo "image=ghcr.io/dune-daq/candidate-release-alma9:latest" >> $GITHUB_OUTPUT
          elif [[ "$TARGET_BRANCH" =~ ^patch/.* ]]; then
            echo "image=ghcr.io/dune-daq/stable-release-alma9:latest" >> $GITHUB_OUTPUT
          else
            echo "image=ghcr.io/dune-daq/nightly-release-alma9:development_v5" >> $GITHUB_OUTPUT
          fi

  Build_against_dev_release:
    needs: Determine_image
    name: build_against_dev_on_${{ matrix.os_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ${{ needs.determine_image.outputs.image }}
            os_name: "a9"
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v7
      with:
        repository: DUNE-DAQ/daq-release
        path: daq-release

    - uses: cvmfs-contrib/github-action-cvmfs@d93d881391926e8146776c13345c3e23d6393acd
      with:
        cvmfs_repositories: 'dunedaq-development.opensciencegrid.org'

    - name: Pull build image
      run: docker pull ${{ needs.determine_image.outputs.image }}
        
    - id: get_release_info
      run: |
          echo "Caller branch is " "$CALLER_BRANCH"
          echo "Target branch is " "$TARGET_BRANCH"

          extra_dbt_args=""
          if [[ ${{ needs.determine_image.outputs.image }} =~ ^.*stable.* ]]; then
            release_name=$( ls -tr /cvmfs/dunedaq.opensciencegrid.org/spack/releases/ | grep fddaq | tail -1 )
          elif [[ ${{ needs.determine_image.outputs.image }} =~ ^.*candidate.* ]]; then
            extra_dbt_args="-b candidate"
            release_name=$( ls -tr /cvmfs/dunedaq-development.opensciencegrid.org/candidates/ | grep fddaq | tail -1 )
          else
            extra_dbt_args="-n"
            release_name=$( ls -tr /cvmfs/dunedaq-development.opensciencegrid.org/nightly/ | grep fddaq | tail -1 )
          fi

          echo "extra_dbt_args=$extra_dbt_args" >> "$GITHUB_OUTPUT"
          echo "release_name=$release_name"     >> "$GITHUB_OUTPUT"

    - name: checkout package for CI
      uses: actions/checkout@v7
      with:
        path: ${{ github.repository }}

    - name: Generate dbt wrapper script
      run: |
        cat << 'EOF' > dbt_wrapper.sh
        #!/bin/bash
        source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
        setup_dbt latest
        cd /ghw/dev-${{ matrix.os_name }}
        source env.sh
        if [[ -d ".sourcecode/dbe" ]]; then
          spack load dbe
        fi
        exec "$@"
        EOF
        
        chmod +x dbt_wrapper.sh
        cat dbt_wrapper.sh

    - name: setup build area
      run: |
        BRANCH="$CALLER_BRANCH"

        cat << EOF > setup_build_area.sh
        #!/bin/bash

        source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
        setup_dbt latest

        dbt-create ${{ steps.get_release_info.outputs.extra_dbt_args }} \
                    ${{ steps.get_release_info.outputs.release_name}} \
                    dev-${{ matrix.os_name }}
        cd dev-${{ matrix.os_name }}
        source env.sh

        cd sourcecode
        if [[ "$CALLER_BRANCH" == "$TARGET_BRANCH" ]]; then
          cp -pr /ghw/DUNE-DAQ/$REPO .
        else   # Someone opened a PR
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          /ghw/daq-release/scripts/clone_all_packages_with_branch.py --branch $CALLER_BRANCH --package-group coredaq
          /ghw/daq-release/scripts/clone_all_packages_with_branch.py --branch $CALLER_BRANCH --package-group fddaq
        fi

        dbt-workarea-env
        dbt-build
        EOF

        chmod +x setup_build_area.sh
        cat setup_build_area.sh

        docker run --rm \
          -v /cvmfs:/cvmfs:shared \
          -v "${GITHUB_WORKSPACE}:/ghw" \
          -w /ghw \
          ${{ needs.determine_image.outputs.image }} \
          /ghw/setup_build_area.sh

        pwd
        ls -lrt

    - name: upload build log file
      uses: actions/upload-artifact@v7
      with:
        name: build_log_${{ matrix.os_name }}
        path: ${{ github.workspace }}/dev-${{ matrix.os_name }}/log/build*.log

    - name: Run linting
      run: |
        docker run --rm \
          -v /cvmfs:/cvmfs:shared \
          -v "${GITHUB_WORKSPACE}:/ghw" \
          -w /ghw \
          ${{ needs.determine_image.outputs.image }} \
          /ghw/dbt_wrapper.sh dbt-build --lint $REPO

    - name: set linting artifact name
      id: set_artifact_name
      run: |
        linting_artifact_name="pull_request_linting_results"
        if [[ "${{ inputs.caller_event_name }}" == "schedule" ]]; then
          linting_artifact_name="nightly_linting_results"
        fi

        linting_file_path=$(find ${{ github.workspace }}/dev-${{ matrix.os_name }}/log/ -name ${REPO}_linting.log | tail -n 1)
        if [[ ! -f "$linting_file_path" ]]; then
          echo "No file named ${REPO}_linting.log found"
          exit 15
        fi

        echo "linting_artifact_name=$linting_artifact_name" >> "$GITHUB_OUTPUT"
        echo "linting_file_path=$linting_file_path" >> "$GITHUB_OUTPUT"

    - name: upload linting log file
      uses: actions/upload-artifact@v7
      with:
        name: ${{ steps.set_artifact_name.outputs.linting_artifact_name }}
        path: ${{ steps.set_artifact_name.outputs.linting_file_path }}

    - name: Run unit tests
      run: |
        docker run --rm \
          -v /cvmfs:/cvmfs:shared \
          -v "${GITHUB_WORKSPACE}:/ghw" \
          -w /ghw \
          ${{ needs.determine_image.outputs.image }} \
          /ghw/dbt_wrapper.sh dbt-build --unittest $REPO

    - name: Get unit test summary path
      id: unit_test_summary
      run: |
        summary_file_path=$(find . -name unit_test_summary.log -type f)
        ./daq-release/scripts/github-ci/parse_unit_test_summary.sh $summary_file_path | tee $GITHUB_STEP_SUMMARY
        echo "summary_file_path=$summary_file_path" >> "$GITHUB_OUTPUT"

    - name: upload unit test summary file
      uses: actions/upload-artifact@v7
      with:
        if-no-files-found: error
        name: unit_test_summary
        path: ${{ steps.unit_test_summary.outputs.summary_file_path }}
  
  compare_linting_results:
    if: ${{ inputs.caller_event_name == 'pull_request' }}
    needs: Build_against_dev_release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Get ID of latest nightly run
      id: latest_nightly
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        run_id=$(gh run list \
          --repo ${{ github.repository }} \
          --workflow dunedaq-develop-cpp-ci.yml \
          --event schedule \
          --limit 1 \
          --json databaseId \
          --jq '.[0].databaseId')

        echo "Comparing results to those from run_id=$run_id"
        echo "run_id=$run_id" >> "$GITHUB_OUTPUT"

    - name: Download latest nightly linting results
      uses: actions/download-artifact@v8
      with:
        github-token: ${{ github.token }}
        name: nightly_linting_results
        path: nightly_linting
        run-id: ${{ steps.latest_nightly.outputs.run_id }}

    - name: Download pull request linting results
      uses: actions/download-artifact@v8
      with:
        name: pull_request_linting_results
        path: pull_request_linting

    - name: Compare linting results
      id: compare
      run: |
        normalize_lint() {
          sed -E '
            s#^/[^ ]*/(sourcecode/.*)#\1#;     # drop leading absolute path before sourcecode/
            s#:[0-9]+:[0-9]+:#:#g;             # drop :line:col:
            s#:[0-9]+:#:#g;                    # drop :line:
            /^[ ]*[0-9]+[ ]\|/d;               # Remove lines starting with " line | "
            /^Total errors found:/d;           # drop summary
          ' "$1" |
          { grep -E "(^|/)${REPO}(/|:)" || true; } |  # keep only lines related to this package
          { grep -E '\[[^][]+\]' || true; } |  # keep only lines with a [check]
          sort -u
        }

        diff_file_name=linting_diff.txt
        pr_linting_results_file=$(find pull_request_linting/ -name "${REPO}_linting.log" | tail -n 1)
        nightly_linting_results_file=$(find nightly_linting/ -name "${REPO}_linting.log" | tail -n 1)

        if [[ ! -f "$pr_linting_results_file" ]]; then
          echo "ERROR: No PR linting results file found"
          exit 11
        fi
        if [[ ! -f "$nightly_linting_results_file" ]]; then
          echo "ERROR: No nightly linting results file found"
          exit 12
        fi

        echo "Pull request linting file: $pr_linting_results_file"
        echo "Nightly linting file: $nightly_linting_results_file"

        nightly_norm=$(mktemp)
        pr_norm=$(mktemp)

        normalize_lint "$nightly_linting_results_file" > "$nightly_norm"
        normalize_lint "$pr_linting_results_file" > "$pr_norm"

        comm -13 "$nightly_norm" "$pr_norm" > "$diff_file_name"

        if [[ -s "$diff_file_name" ]]; then
          echo "ERROR: This PR introduces new linting errors:"
          cat "$diff_file_name"
          echo "diff_exists=true" >> "$GITHUB_OUTPUT"
          echo "diff_file_name=$diff_file_name" >> "$GITHUB_OUTPUT"
          exit 13
        else
          diff_exists="false"
        fi

    - name: upload linting diff file
      if: ${{ steps.compare.outputs.diff_exists == 'true' }}
      uses: actions/upload-artifact@v7
      with:
        name: linting_diff
        path: ${{ steps.compare.outputs.diff_file_name }}

  check_docs_links:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v7
    - name: Check links
      uses: lycheeverse/lychee-action@39066c6d1f0de280863a3760160617e188b607ad
      with:
        fail: false
        failIfEmpty: false

    - name: Upload link checker log
      uses: actions/upload-artifact@v7
      with:
        name: link_checker_log
        path: ./lychee/out.md
